spring:
  datasource:
    generate-unique-name: false
    name: bank

    datasource:
      url: "jdbc:h2:mem:bank"
      username: sa
      password:

    jpa:
      show-sql: true
      generate-ddl: false
      hibernate:
        ddl-auto: update
      properties:
        hibernate.jdbc.lob:
          non_contextual_creation: true

    flyway:
      baseline-on-migrate: 'true'
      schemas: data
      locations: classpath:db/migration