spring:
  datasource:
    generate-unique-name: false
    name: bank

    datasource:
      url: "jdbc:h2:mem:bank"
      username: sa
      password:

    flyway:
      baseline-on-migrate: 'true'
      schemas: data
      locations: classpath:db/migration